version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pigmoney-web
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "3002:3000" 
    networks:
      - webnet

networks:
  webnet: